In [1]:
import numpy as np 

print(np.__version__)

1.25.1


In [2]:
array = np.array([1, 2, 3, 4])
print(type(array))

<class 'numpy.ndarray'>


In [4]:
array = array * 2
array

array([ 4,  8, 12, 16])

In [5]:
print(array.ndim)

1


In [7]:
array = np.array([[2, 3, 4],
                 [5, 7, 8],
                 [1, 2, 5]])

print(array.ndim)

2


In [8]:
print(array.shape)

(3, 3)


In [10]:
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
     [['J', 'K', 'L'],['M', 'N', 'O'],['P', 'Q', 'R']],
     [['S', 'T', 'U'],['V', 'W', 'X'],['Y', 'Z', ' ']]])

print(array.shape)

(3, 3, 3)


In [11]:
print(array[0, 0, 1])

B


In [12]:
print(array[0, 1, 1])

E


In [15]:
from numpy.core import multiarray
word = array[0, 0, 1] + array[0, 0, 0] + array[1, 0, 2] + array[1, 0, 2] + array[1, 1, 2] + array[1, 1, 2] + array[1, 1, 1]
print(word)

BALLOON


### slicing

ROW SELECTION

In [16]:
array = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

print(array[0])

[1 2 3 4]


In [17]:
print(array[2])

[ 9 10 11 12]


In [18]:
print(array[0:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
print(array[1:4])

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [20]:
print(array[1:])

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [21]:
print(array[0:4])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [22]:
print(array[0:4:2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [23]:
print(array[::-2])

[[13 14 15 16]
 [ 5  6  7  8]]


COLUMN SELECTION

In [24]:
print(array[:, 0])

[ 1  5  9 13]


In [25]:
print(array[:, 1])

[ 2  6 10 14]


In [26]:
print(array[:, 2])

[ 3  7 11 15]


In [27]:
print(array[:, -1])

[ 4  8 12 16]


In [28]:
print(array[:, -2])

[ 3  7 11 15]


In [29]:
print(array[:, 0:3])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [30]:
print(array[:, 1:4])

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [31]:
print(array[:, 1::2])

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [32]:
print(array[:, ::-1])

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [33]:
print(array[0:2, 0:2])

[[1 2]
 [5 6]]


In [34]:
print(array[0:2, 2:])

[[3 4]
 [7 8]]


In [35]:
print(array[2:, 0:2])

[[ 9 10]
 [13 14]]


In [36]:
print(array[2:, 2:])

[[11 12]
 [15 16]]


### Arithmetic 

SCALAR FUNCTIONS

In [37]:
array = np.array([1, 2, 3])

print(array + 1)

[2 3 4]


In [39]:
print(array - 2)
print(array * 3)
print(array / 4)
print(array ** 5)

[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


VECTORIZED FUNCTIONS

In [40]:
print(np.sqrt(array))

[1.         1.41421356 1.73205081]


In [41]:
array = np.array([1.01, 2.6, 3.99])
print(np.round(array))
print(np.ceil(array))

[1. 3. 4.]
[2. 3. 4.]


In [43]:
print(np.pi)  ## value of pi

3.141592653589793


In [44]:
radii = np.array([1, 2, 3])
print(np.pi * radii ** 2)

[ 3.14159265 12.56637061 28.27433388]


ELEMENT-WISE ARITHMETIC

In [45]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


COMPARISON OPERATORS

In [48]:
scores = np.array([91, 55, 100, 73, 83, 64])

print(scores == 100)
print(scores >= 60)
print(scores < 60)

[False False  True False False False]
[ True False  True  True  True  True]
[False  True False False False False]


In [49]:
scores[scores < 60] = 0
print(scores)

[ 91   0 100  73  83  64]


### Broadcasting

In [52]:
array1 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
array2 = np.array([[1], [2], [3], [4]])

print(array1.shape)
print(array2.shape)

(4, 4)
(4, 1)


In [53]:
print(array1 * array2)

[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 64]]


In [54]:
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array2 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])

print(array1 * array2)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


### Aggregate functions

##### Aggregate functions summarizes the data and typically returns a single value

In [57]:
array = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))
print(np.min(array))
print(np.max(array))
print(np.argmin(array))
print(np.argmax(array))


55
5.5
2.8722813232690143
8.25
1
10
0
9


In [61]:
print(np.sum(array, axis=0)) ## sum of columns
print(np.sum(array, axis=1)) ## sum of rows

[ 7  9 11 13 15]
[15 40]


### Filtering

In [ ]:
ages = np.array([[21, 17, 19, 20, 16, 86, 50],
                 [39, 22, 15, 99, 18, 65, 21]])

teenagers = ages[ages < 18]
adults = ages[(ages >= 18) & (ages <= 65)]
olds = ages[ages >= 80]

print(teenagers)
print(adults)
print(olds)


[17 16 15]
[21 19 20 50 39 22 18 65 21]
[86 99]


In [72]:
adults = np.where(ages >= 18, ages, 0)
print(adults)

[[21  0 19 20  0 86 50]
 [39 22  0 99 18 65 21]]


### Random Numbers

In [106]:
import dataclasses
rng = np.random.default_rng()
#rng = np.random.default_rng(seed=1)

print(rng.integers(1, 7))

6


In [99]:
print(rng.integers(low=1, high=101, size=4))
print(rng.integers(low=1, high=101, size=(3, 2)))

[79 45 87 98]
[[82 21]
 [75 71]
 [96  9]]


In [120]:
#np.random.seed(seed=1)

print(np.random.uniform(low=-1, high=1, size=(3, 3)))

[[-0.08865277 -0.22365754  0.52009293]
 [ 0.2776564   0.82041437  0.51208965]
 [-0.21147325 -0.89641043  0.59462314]]


In [121]:
array = np.array([1, 2, 3, 4, 5])
rng.shuffle(array)
print(array)

[4 2 1 5 3]


In [141]:
fruits = np.array(["mango", "apple", "banana", "orange", "guava", "coconut"])
fruits= rng.choice(fruits, size=3)
print(fruits)

['orange' 'coconut' 'mango']
